image:
  file: devops/dockerfiles/.gitpod.Dockerfile
tasks:
  - name: install the remote-signer
    before: |
      sudo sh -c 'curl https://ipfs.anagolay.network/ipfs/QmVwR17T5oT4SsH1gb8T9L9gHe5CsJz2iwhbhWCwPPHgHR > /usr/local/bin/remote-signer && chmod +x /usr/local/bin/remote-signer' \
      && git config --global gpg.program "remote-signer" \
      && git config --global commit.gpgsign true
vscode:
  extensions:
    - rust-lang.rust
    - tamasfe.even-better-toml
    - belfz.search-crates-io
    - serayuzgur.crates
    - vadimcn.vscode-lldb
    - redhat.vscode-yaml
    - mhutchie.git-graph
