tasks:
  - name: instal deps
    init: |
      bash ./scripts/setup-dev-env.sh \
      && gp env SCCACHE_S3_KEY_PREFIX=anagolay_runtime \
      && gp env RUSTC_WRAPPER=/usr/local/bin/sccache \
      && sccache --show-stats

vscode:
  extensions:
    - rust-lang.rust
    - tamasfe.even-better-toml
    - belfz.search-crates-io
    - serayuzgur.crates
    - vadimcn.vscode-lldb
    - redhat.vscode-yaml
    - mhutchie.git-graph
