[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    # 'implemented-operations/sn-cid',
    'pallets/sensio',
    'pallets/operations',
    'pallets/statements',
    'pallets/rules',
    'pallets/poe',
    'runtime'
]
