[workspace]
members = [
  'node',
  'pallets/anagolay-support',
  'pallets/operations',
  #  'pallets/statements',
  'pallets/workflows',
  #  'pallets/poe',
  'runtime',
]

[profile.release]
opt-level = 3
lto = true
panic = 'unwind'
