version: "3.5"
services:
  an-chain-code:
    # user: $UID
    user: "${UID}:${UID}"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    build:
      context: .
      dockerfile: devops/dockerfiles/.devcontainer.Dockerfile
      args:
        VARIANT: bullseye
        USER_UID: $UID
    working_dir: /app
    volumes:
      - .:/app:cached
      - anagolay_cargo:/usr/local/cargo
      ## https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
      # - vscode_extensions:/home/vscode/.vscode-server:cached
    command: sleep infinity

volumes:
  anagolay_cargo:
  vscode_extensions:
