version: "3.5"
services:
  code:
    # ports:
    #   - 30333:30333
    #   - 9933:9933
    #   - 9944:9944
    #   - 9615:9615
    user: "${UID}:${UID}"
    environment: 
      - CARGO_INCREMENTAL=0
      - RUSTC_WRAPPER=sccache
      - SCCACHE_DIR=/home/vscode/.cache/sccache
    env_file: ./.env
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    build:
      context: .
      dockerfile: devops/workspaces/.devcontainer.Dockerfile
      args:
        VARIANT: bullseye
        USER_UID: $UID
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      # - anagolay_cargo:/usr/local/cargo
      ## https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
      # - vscode_extensions:/home/vscode/.vscode-server:cached
    command: sleep infinity

# volumes:
#   anagolay_cargo:
#   vscode_extensions:
