tab_spaces = 2
reorder_imports = true
newline_style = "Unix"
# hard_tabs = true
max_width = 120
comment_width = 100
wrap_comments = true

imports_granularity = "Crate"
binop_separator = "Back"
use_field_init_shorthand = true
