version: "3"
services:
  code:
    image: woss/substrate_devcontainer:latest
    # image: paritytech/ci-linux:9575dfcd-20210727
    env_file: main.env
    # environment:
    # - CARGO_HOME=/app/.cargo
    restart: unless-stopped
    # On Linux, this will prevent new files getting created as root, but you
    # may need to update the USER_UID and USER_GID in `Dockerfile` to match
    # your user if not 1000.
    # user: $UID
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    build:
      context: .
      dockerfile: devcontainer.base.Dockerfile
    # args:
    # USER_UID: $UID
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    working_dir: /app
    volumes:
      - .:/app:cached
      # - anagolay_cargo:/usr/local/cargo
      ## https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
      - vscode_extensions:/home/vscode/.vscode-server
      # ! LINUX HOST ONLY
      # copies your ssh credentials, to be able to use them from within the container
      # (see: https://code.visualstudio.com/docs/remote/containers#_sharing-git-credentials-with-your-container)
      - $HOME/.ssh:/tmp/.ssh:ro
      # - type: bind
      #   source: ./.local
      #   target: /root/.local
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  node:
    image: anagolay/node:${VERSION}
    env_file: main.env
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: node
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    volumes:
      - anagolay_data:/data
    command: anagolay --dev --no-telemetry --rpc-external --unsafe-ws-external --rpc-cors all
volumes:
  anagolay_data:
  anagolay_cargo:
  vscode_extensions:
