[package]
authors = ['urn:pgp:d1f5e247a976f1e3c14f0a437a6db9962ef3978e']
repository = 'https://gitlab.com/sensio_group/network-node/'
homepage = 'https://sensio.network'
edition = '2018'
license = 'Apache 2.0'
name = 'pallet-poe'
version = '0.1.0'

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.2.0'

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.4'

[dependencies.safe-mix]
default-features = false
version = '1.0.1'

[dependencies.system]
default-features = false
package = "frame-system"
version = '2.0.0-alpha.4'

[dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.4'

[dependencies.sp-io]
default-features = false
features = ["disable_panic_handler", "disable_oom"]
version = '2.0.0-alpha.4'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.4'

[dependencies.sp-std]
default-features = false
version = '2.0.0-alpha.4'

[dependencies.timestamp]
default-features = false
package = 'pallet-timestamp'
version = '2.0.0-alpha.4'

[dependencies.cid]
default-features = false
version = "0.4.0"

[dependencies.multihash]
default-features = false
version = "0.10.1"

[dependencies.multibase]
default-features = false
version = "0.8.0"

[features]
default = ['std']
std = [
  'parity-scale-codec/std',
  'frame-support/std',
  'safe-mix/std',
  'system/std',
  'sp-std/std',
  'sp-runtime/std',
  'sp-core/std',
]
